#!/bin/bash

DISCS_PATH=/home/fac_files/lnls-sirius/discs-management
REMOTE_PATH=fernando-linux:/home/fac_files/backup-discs/daily/

if [ -d  $DISCS_PATH ]; then
    cd $DISCS_PATH
    ./discs-run.sh backup
    find ./backup-discs -mtime +30 -type f -delete
    scp -rp  backup-discs/*$(date "+%Y-%m-%d")*.gz $REMOTE_PATH
fi
